"""Initialisation

Revision ID: 5337c729bc2f
Revises: 
Create Date: 2025-01-27 19:49:19.227661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5337c729bc2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Platform',
    sa.Column('PlatformID', sa.Integer(), nullable=False),
    sa.Column('Balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('PlatformID')
    )
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('EmailAddress', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('UserType', sa.Enum('Customer', 'Restaurant', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('EmailAddress')
    )
    op.create_table('Customers',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=False),
    sa.Column('PostNumber', sa.String(length=10), nullable=False),
    sa.Column('Balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('Restaurants',
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=False),
    sa.Column('PostalCode', sa.String(length=10), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('ImageURL', sa.String(length=255), nullable=True),
    sa.Column('OpenTime', sa.Time(), nullable=False),
    sa.Column('CloseTime', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('RestaurantID')
    )
    op.create_table('DeliveryAreas',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.Column('PostalCode', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['RestaurantID'], ['Restaurants.RestaurantID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('MenuItems',
    sa.Column('MenuItemID', sa.Integer(), nullable=False),
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Category', sa.String(), nullable=False),
    sa.Column('ImageURL', sa.String(), nullable=True),
    sa.Column('IsAvailable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['RestaurantID'], ['Restaurants.RestaurantID'], ),
    sa.PrimaryKeyConstraint('MenuItemID')
    )
    op.create_table('OpeningHours',
    sa.Column('OpeningHourID', sa.Integer(), nullable=False),
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.Column('DayOfWeek', sa.Integer(), nullable=False),
    sa.Column('OpenTime', sa.String(), nullable=False),
    sa.Column('CloseTime', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['RestaurantID'], ['Restaurants.RestaurantID'], ),
    sa.PrimaryKeyConstraint('OpeningHourID')
    )
    op.create_table('Orders',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PlatformFee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('RestaurantAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['RestaurantID'], ['Restaurants.RestaurantID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('CartItems',
    sa.Column('CartItemID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('MenuItemID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MenuItemID'], ['MenuItems.MenuItemID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('CartItemID')
    )
    op.create_table('OrderItems',
    sa.Column('OrderItemID', sa.Integer(), nullable=False),
    sa.Column('MenuItemName', sa.String(length=255), nullable=False),
    sa.Column('MenuItemPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['Orders.OrderID'], ),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderItems')
    op.drop_table('CartItems')
    op.drop_table('Orders')
    op.drop_table('OpeningHours')
    op.drop_table('MenuItems')
    op.drop_table('DeliveryAreas')
    op.drop_table('Restaurants')
    op.drop_table('Customers')
    op.drop_table('Users')
    op.drop_table('Platform')
    # ### end Alembic commands ###
